# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
<<<<<<< HEAD
    branches: [Nic]
    #branches:[Afifi]
=======
    branches: [main]
>>>>>>> 4716120dc968ca2783aa00743c2964700c1651e2

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - run: npm i --force
      - run: CI=false npm run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./build/
          remote_path: /var/www/my-app/
          remote_host: ec2-18-143-49-254.ap-southeast-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.MY_SECRET }}"
